#%RAML 1.0
title: Sample API

/version:
  get:
    description: Get version.
    responses:
      200:
        body:
          application/json:
          
/reports:
  post:
    description: Generates reports.
    responses:
      200:
        body:
          application/json: